USE DATABASE SMART_CITY_AQI;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE AQI_SUMMARY AS
SELECT
    CITY,
    SENSOR_ID,
    COUNT(*) AS TOTAL_READINGS,
    ROUND(AVG(PM25),2) AS AVG_PM25,
    ROUND(AVG(PM10),2) AS AVG_PM10,
    ROUND(AVG(CO),2) AS AVG_CO,
    ROUND(AVG(NO2),2) AS AVG_NO2,
    ROUND(AVG(SO2),2) AS AVG_SO2,
    ROUND(AVG(O3),2) AS AVG_O3,
    ROUND(AVG(TEMPERATURE),2) AS AVG_TEMPERATURE,
    ROUND(AVG(HUMIDITY),2) AS AVG_HUMIDITY,
    ROUND(AVG(WIND_SPEED),2) AS AVG_WIND_SPEED,
    ROUND(AVG(AQI),2) AS AVG_AQI
FROM SMART_CITY_AQI.CLEAN.CLEAN_AQI
GROUP BY CITY, SENSOR_ID
ORDER BY AVG_AQI DESC;