USE DATABASE SMART_CITY_AQI;
USE SCHEMA CLEAN;

CREATE OR REPLACE TABLE CLEAN_AQI AS
SELECT
    ID,
    SENSOR_ID,
    CITY,
    LATITUDE,
    LONGITUDE,
    PM25,
    PM10,
    CO,
    NO2,
    SO2,
    O3,
    TEMPERATURE,
    HUMIDITY,
    WIND_SPEED,
    AQI,
    AQI_CATEGORY,
    HEALTH_RISK,
    READING_TIME
FROM SMART_CITY_AQI.RAW.IOT_READINGS
WHERE PM25 IS NOT NULL
  AND PM10 IS NOT NULL
  AND AQI IS NOT NULL;